experiment:
  max_cost: 1.0
  enable_autoprompt: False

executor:
  max_rounds: 100
  model: gemma2:2b-instruct-q4_0
  temperature: 1.0
  max_tokens: 4096
  prompt: prompts/base_single_executor.yaml
  toolset:
    - run_command
    - create_file
    - disassemble
    - decompile
    - submit_flag
    - giveup
autoprompter:
  max_rounds: 5
  model: gemma2:2b-instruct-q4_0
  temperature: 1.0
  max_tokens: 4096
  prompt: prompts/autoprompt_prompt.yaml
  toolset:
    - run_command
    - generate_prompt
