experiment:
  max_cost: 1.0
  enable_autoprompt: False

executor:
  max_rounds: 100
  model: qwen2.5-coder:14b
  temperature: 0.5
  max_tokens: 4096
  prompt: prompts/pwn_single_executor.yaml
  toolset:
    - run_command
    - create_file
    # - disassemble
    # - decompile
    - submit_flag
    - giveup
autoprompter:
  max_rounds: 5
  model: qwen2.5-coder:14b
  temperature: 0.5
  max_tokens: 8192
  prompt: prompts/autoprompt_prompt.yaml
  toolset:
    - run_command
    - generate_prompt
