experiment:
  max_cost: 1.0
  enable_autoprompt: False

planner:
  max_rounds: 30
  model: MFDoom/deepseek-r1-tool-calling:8b
  temperature: 1.0
  max_tokens: 4096
  prompt: prompts/pwn_planner_prompt.yaml
  toolset:
    - run_command
    - submit_flag
    - giveup
    - delegate
executor:
  max_rounds: 100
  model: qwen2.5-coder:14b
  temperature: 1.0
  max_tokens: 4096
  len_observations: 5
  prompt: prompts/pwn_executor_prompt.yaml
  toolset:
    - run_command
    - finish_task
    - disassemble
    - decompile
    - create_file
autoprompter:
  max_rounds: 5
  model: MFDoom/deepseek-r1-tool-calling:8b
  temperature: 1.0
  max_tokens: 4096
  prompt: prompts/autoprompt_prompt.yaml
  toolset:
    - run_command
    - generate_prompt
